#!/bin/bash

set -e


# Check for -s flag to skip interactive mode
SKIP_INTERACTIVE=false
if [ "$1" = "-s" ]; then
  SKIP_INTERACTIVE=true
fi

# Check working directory
if [ $HOME == $PWD ]; then
  echo "Error: can not put this project in home directory!"
  exit -1
fi

if [ ! -f "$PWD/setup" ]; then
  echo "Error: please run this command under project directory!"
  exit -1
fi

# Check dependency
command -v vim >/dev/null 2>&1 || { echo >&2 "I require vim but it's not installed.  Aborting."; exit 1; }
command -v zsh >/dev/null 2>&1 || { echo >&2 "I require zsh but it's not installed.  Aborting."; exit 1; }
command -v ctags >/dev/null 2>&1 || { echo >&2 "I require ctags but it's not installed.  Aborting."; exit 1; }

# Reset submodules
rm -rf .oh-my-zsh
rm -rf .vim
rm -rf .zsh-custom

# Init submodules
git submodule init
git submodule update

# Link to home
rm -rf $HOME/.zshrc && ln -fs $PWD/.zshrc $HOME/.zshrc
rm -rf $HOME/.zsh-custom && ln -fs $PWD/.zsh-custom $HOME/.zsh-custom
rm -rf $HOME/.oh-my-zsh && ln -fs $PWD/.oh-my-zsh $HOME/.oh-my-zsh
rm -rf $HOME/.bin && ln -fs $PWD/.bin $HOME/.bin
rm -rf $HOME/.alias_profile && ln -fs $PWD/.alias_profile $HOME/.alias_profile
rm -rf $HOME/.gitconfig && ln -fs $PWD/.gitconfig $HOME/.gitconfig
rm -rf $HOME/.gitconfig_trip && ln -fs $PWD/.gitconfig_trip $HOME/.gitconfig_trip
rm -rf $HOME/.gitignore && ln -fs $PWD/.gitignore $HOME/.gitignore
rm -rf $HOME/.gitignore_global && ln -fs $PWD/.gitignore_global $HOME/.gitignore_global
rm -rf $HOME/.gitmodules && ln -fs $PWD/.gitmodules $HOME/.gitmodules
rm -rf $HOME/.vim && ln -fs $PWD/.vim $HOME/.vim
rm -rf $HOME/.vimrc && ln -fs $PWD/.vimrc $HOME/.vimrc
rm -rf $HOME/.starship.toml && ln -fs $PWD/.starship.toml $HOME/.starship.toml
rm -rf $HOME/.agents && ln -fs $PWD/.agents $HOME/.agents
mkdir -p $HOME/.config/mise && rm -rf $HOME/.config/mise/config.toml && ln -fs $PWD/mise-config.toml $HOME/.config/mise/config.toml

# Install vim plugins
vim +PluginInstall +qall

# Change default shell
if [ "$SKIP_INTERACTIVE" = true ]; then
  echo "Skipping interactive shell change due to -s flag"
else
  echo "Input password for change default shell"
  chsh -s `which zsh`
fi
