#!/bin/bash

set -e

# Check working directory
if [ $HOME == $PWD ]; then
  echo "Error: can not put this project in home directory!"
  exit -1
fi

if [ ! -f "$PWD/setup" ]; then
  echo "Error: please run this command under project directory!"
  exit -1
fi

# Check dependency
command -v vim >/dev/null 2>&1 || { echo >&2 "I require vim but it's not installed.  Aborting."; exit 1; }
command -v ctags >/dev/null 2>&1 || { echo >&2 "I require ctags but it's not installed.  Aborting."; exit 1; }

# Reset submodules
rm -rf .oh-my-zsh
rm -rf .vim/bundle/Vundle.vim
rm -rf .zsh-plugins
rm -rf .zsh-themes

# Init submodules
git submodule init
git submodule update

# Link plugins and themes
ln -fs $PWD/.zsh-plugins/* $PWD/.oh-my-zsh/custom/plugins
ln -fs $PWD/.zsh-themes/* $PWD/.oh-my-zsh/custom/themes

# Link to home
ls -A | grep -v '^setup$' | grep -v '^README.md$' | grep -v '^.git$' | xargs -I {} rm -rf $HOME/{}
ls -A | grep -v '^setup$' | grep -v '^README.md$' | grep -v '^.git$' | xargs -I {} ln -fs $PWD/{} $HOME/{}

# Install vim plugins
vim +PluginInstall +qall
