#!/bin/bash

npx skills add http://git.dev.sh.ctripcorp.com/framework/monitor-team-skills.git -g -y
npx skills add sanyuan0704/sanyuan-skills -g -y --skill code-review-expert
npx skills add sundial-org/awesome-openclaw-skills -g -y --skill glab
npx skills add larksuite/cli -g -y
npx skills add microsoft/playwright-cli -g -y --skill playwright-cli
npx skills add http://git.dev.sh.ctripcorp.com/framework/bat-mcp-function.git -g -y