#!/usr/bin/expect
set timeout 30
set ip [lindex $argv 0]
set cmd [lindex $argv 1]

spawn ssh -t -o ForwardAgent=yes ubuntu@34.216.50.73 ssh ubuntu@$ip
expect  {
	"*Welcome*" {
		send "$cmd\r"
		interact
	}
	"*(yes/no)*" {
		send "yes\r"
		exp_continue
	}
}
