#!/bin/bash

# alias '??'="AI_STYLE=simple ask-ai"
# alias '???'="AI_STYLE=full ask-ai"
# 
# example 1: ?? simple python3 http server
# example 2: git push |& ???

_PROMPT="
role: 你现在是一名资深的软件工程师，你擅长解决技术问题，并具有优秀的逻辑思维能力，请在这个角色下为我解答以下问题;
language: 简体中文;
operating system: `uname -a`;
shell: `echo $SHELL`;"

if [ "$AI_STYLE" = "simple" ]; then
    _PROMPT="${_PROMPT} style: 回答简洁不需要过多解释，尽量用一句话解决问题，尽量直接说出相关代码;"
fi

_INPUT="$@"
if [ ! -t 0 ]; then
    while read -r line; do
        _INPUT="$_INPUT\n$line"
    done
fi

mods --quiet --api ollama --model $OLLAMA_DEFAULT_MODEL --prompt "$_PROMPT" "$_INPUT"