#!/usr/bin/env python3

import re
import sys


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: custom-phrase <format(apple)> <file> > <output>")
        print("Example: custom-phrase apple custom_phrase.txt > custom_phrase.plist")
        sys.exit(1)

    format = sys.argv[1]
    if format == "apple":
        print("""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>""")
        with open(sys.argv[2], "r") as f:
            for line in f:
                if not line.strip():
                    continue
                pair = re.split(r'[\s\t]+', line.strip())
                if not len(pair) == 2:
                    continue
                print("	<dict>")
                print("		<key>phrase</key>")
                print(f"		<string>{pair[0]}</string>")
                print("		<key>shortcut</key>")
                print(f"		<string>{pair[1]}</string>")
                print("	</dict>")
        print("""</array>
</plist>""")