#!/bin/bash

# Dir Profile
export PATH=$ORIGIN_PATH
DIR_PROFILES=()
DIR_TMP=$PWD
while [ "$DIR_TMP" != "/" ]; do
    if [ -f "$DIR_TMP/.dir_profile" ]; then
        DIR_PROFILES+=("$DIR_TMP/.dir_profile")
    fi
    DIR_TMP=`dirname "$DIR_TMP"`
done

for ((i=${#DIR_PROFILES[@]}; i>=1; i--)); do
    echo -e "\033[30;1mapply dir profile: ${DIR_PROFILES[i]}\033[0m"
    source "${DIR_PROFILES[i]}"
done
unset DIR_PROFILES
unset DIR_TMP