#!/bin/bash

MOUNT_SOURCE_HOME=/Volumes/External

MOUNT_TARGECTS=(
    "/Users/dozer/.minikube"
    "/Users/dozer/Library/Containers/com.docker.docker"
    "/Users/dozer/Projects"
)

for t in ${MOUNT_TARGECTS[@]}; do
    mkdir -p "${MOUNT_SOURCE_HOME}${t}"
    rm -r "${t}"
    ln -s "${MOUNT_SOURCE_HOME}${t}" "${t}"
done