#!/bin/bash

kube-cluster default
kubectl create namespace istio-system || true
kubectl label namespace default istio-injection=enabled --overwrite=true
istioctl install -y -f -<< EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-default
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      concurrency: 1
  profile: default
  hub: docker.io/querycapistio
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            ports:
              - port: 80
                targetPort: 8080
                name: http2
              - port: 15021
                name: status-port
                protocol: TCP
                targetPort: 15021
              - port: 443
                name: https
                protocol: TCP
                targetPort: 8443
              - port: 15443
                name: tls
                protocol: TCP
                targetPort: 15443
              - port: 9090
                targetPort: 9090
                name: grpc
  values:
    global:
      arch:
        arm64: 1
      imagePullPolicy: IfNotPresent
EOF