#!/bin/bash

set -e

kubectl scale deployment/istiod -n istio-system --replicas=0

BUILD_WITH_CONTAINER=0 DEBUG=1 make docker.pilot

docker tag istio/pilot:$(git rev-parse HEAD) istio/pilot:$ISTIO_VERSION

minikube-reload-image istio/pilot:$ISTIO_VERSION

kubectl scale deployment/istiod -n istio-system --replicas=1

sleep 5

kubectl wait --for=condition=ready -n istio-system pod -l app=istiod