#!/bin/bash

kube-cluster default
kubectl create namespace istio-system || true
kubectl label namespace default istio-injection=enabled --overwrite=true
istioctl install -y --force -f -<< EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-default
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      concurrency: 1
  profile: default
  hub: docker.io/querycapistio
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
    egressGateways:
    - name: istio-egressgateway
      enabled: false
  values:
    global:
      arch:
        arm64: 1
      imagePullPolicy: IfNotPresent
EOF