#!/bin/bash

JAVA_HOME="$(mise which java | sed 's|/bin/java||')"
sudo $JAVA_HOME/bin/keytool -J-Duser.language=en -import -alias ctrip -keystore "$JAVA_HOME/jre/lib/security/cacerts" -file "$1" -trustcacerts -storepass changeit 2>&1 > /dev/null
sudo $JAVA_HOME/bin/keytool -J-Duser.language=en -import -alias ctrip -keystore "$JAVA_HOME/lib/security/cacerts" -file "$1" -trustcacerts -storepass changeit 2>&1 > /dev/null
