#!/usr/bin/env node

const value = process.argv[2]
let hashcode = 0;
for (let i = 0; i < value.length; i++) {
    hashcode = (hashcode * 31 + value.charCodeAt(i)) & 0xffffffff;
}
console.log(hashcode);