#!/bin/bash

# check $JAVA_HOME if is jdk8 
if [[ $JAVA_HOME == *"-8."* ]]; then
    sudo $JAVA_HOME/bin/keytool -J-Duser.language=en -import -alias ctrip -keystore "$JAVA_HOME/jre/lib/security/cacerts" -file "$1" -trustcacerts -storepass changeit
else
    sudo $JAVA_HOME/bin/keytool -J-Duser.language=en -import -alias ctrip -keystore "$JAVA_HOME/lib/security/cacerts" -file "$1" -trustcacerts -storepass changeit
fi



