#!/bin/bash

## Load host docker images to Kind on-demand, need to run it after create Kind cluster everytime.
## You pass the group name to this command like: `kind-load-images nginx`

KUBE_CACHED_IMAGES=(
    dozer47528/devops-toolkits-docker:latest,debug
    nginx:stable,debug
    golang:1.15,debug
)

if [[ -d "$ISTIO_HOME" ]] && [[ -x "$(command -v jq)" ]]; then
    KUBE_CACHED_IMAGES+=(
        istio/proxyv2:${ISTIO_VERSION},istio
        istio/pilot:${ISTIO_VERSION},istio
    )
fi

for i in ${KUBE_CACHED_IMAGES[@]}; do
    image=$(echo $i | awk -F ',' '{print $1}')
    group=$(echo $i | awk -F ',' '{print $2}')
    if [[ $1 == $group ]] || [[ $1 == "all" ]]; then
        docker pull $image
        kind load docker-image $image
    fi
done