#!/bin/bash

if [[ -z $1 ]]; then
    echo "Error: please choose a cluster!"
    return 1
fi

uuid=$(uuidgen)

ctrip_clusters=(`kubectl config get-contexts --kubeconfig ~/.kube/clusters/ocid/ctrip -o name`)

if [[ $1 == "default" ]]; then
    cp ${HOME}/.kube/config ~/.tmp/${uuid}
elif [[ $ctrip_clusters == *$1* ]]; then
    cp ${HOME}/.kube/clusters/ocid/ctrip ~/.tmp/${uuid}
    kubectl config use-context --kubeconfig ~/.tmp/${uuid} $1
else
    cp ${HOME}/.kube/clusters/$1 ~/.tmp/${uuid}
fi
chmod 600 ~/.tmp/*
export KUBECONFIG=${HOME}/.tmp/${uuid}