#!/bin/bash

if [[ -z $1 ]]; then
    echo "Error: please choose a cluster!"
    return 1
fi

uuid=$(uuidgen)
if [[ $1 == "default" ]]; then
    cp ${HOME}/.kube/config ~/.tmp/${uuid}
else
    cp ${HOME}/.kube/clusters/$1 ~/.tmp/${uuid}
fi
chmod 600 ~/.tmp/*
export KUBECONFIG=${HOME}/.tmp/${uuid}