#!/bin/bash

help(){
    echo "kube-log <pod-name> [options...]"
    echo " -p, --proxy-container: Select proxy container instead of app container."
    echo " -f, --follow: Specify if the logs should be streamed."
    exit 0
}

FOLLOW=""

while :; do
    if [[ -z "$1" ]]; then
        break
    fi

    case $1 in
        -p|--proxy-container)
        PROXY_CONTAINER="-p"
        ;;
        -f|--follow) FOLLOW="-f"
        ;;
        -h|--help)
        help
        ;;
        *)
        if [[ -z "$POD_NAME" ]]; then
            POD_NAME=$1
        fi
        ;;
    esac
    shift
done

if [[ -z "$POD_NAME" ]]; then
    help
fi

kubectl logs $POD_NAME $FOLLOW -c $(pod-container $POD_NAME $PROXY_CONTAINER)