#!/bin/bash

COMMAND=$1
shift

if [ $COMMAND == "exec" ]; then
    IS_EXEC="1"
fi

SIDECAR_CONTAINER=""
SHELL="/bin/bash"
CMD=""

while :; do
    if [[ -z "$1" ]]; then
        break
    fi

    if [[ $CMD_START == "1" ]]; then
        CMD="$CMD $1"
        shift
        continue
    fi

    case $1 in
        --)
        CMD_START=1
        ;;
        --sh) SHELL="/bin/sh"
        ;;
        -s|--sidecar)
        SIDECAR_CONTAINER="--sidecar"
        ;;
        *)
        COMMAND="$COMMAND $1"
        if [[ "$1" != -* ]] && [[ -z "$POD_NAME" ]]; then
            POD_NAME=$1
        fi
        ;;
    esac
    shift
done

if kubectl $1 --help | grep ", \-\-container" &> /dev/null; then
    COMMAND="$COMMAND --container $(pod-container $POD_NAME $SIDECAR_CONTAINER)"
fi

if [[ -n $IS_EXEC ]]; then
    if [[ -z "$CMD" ]]; then
        COMMAND="$COMMAND -it $SHELL"
    else
        COMMAND="$COMMAND -- $CMD"
    fi
fi

kubectl $COMMAND