#!/bin/bash

cat << EOF | sudo tee /etc/nginx/nginx.conf
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

stream {
  server {
      listen 0.0.0.0:8443;
      proxy_pass $(minikube ip):8443;
  }
}
EOF

sudo systemctl restart nginx
systemctl status nginx.service