#!/bin/bash

KUBE_CACHED_IMAGES=(
    dozer47528/devops-toolkits-docker:latest
    nginx:stable
    golang:1.16
)

if [[ -d "$ISTIO_HOME" ]] && [[ -x "$(command -v jq)" ]]; then
    KUBE_CACHED_IMAGES+=(
        istio/proxyv2:${ISTIO_VERSION}
        istio/pilot:${ISTIO_VERSION}
    )
fi

for i in ${KUBE_CACHED_IMAGES[@]}; do
    docker pull $i
    minikube image load $i
done