#!/usr/bin/env python3
import difflib
import json
import sys

if __name__ == "__main__":
    if sys.stdin.readable():
        data = sys.stdin.read()
        left, right = data.split(" -> ")
        left = json.dumps(json.loads(left.replace("\\\"", "\"")), indent=4, sort_keys=True)
        right = json.dumps(json.loads(right.replace("\\\"", "\"")), indent=4, sort_keys=True)
        for line in difflib.context_diff(left.split("\n"), right.split("\n")):
            print(line)
