#!/usr/bin/osascript

tell application "iTerm"
	activate
	set cmd to "amino-proxy "
	set internalHost to "10.2.11.170"
	set hosts to {"10.2.11.121", "10.2.11.217", "10.2.11.215", "10.2.11.66", "10.2.11.10", "10.2.11.222", "10.2.11.159", "10.2.11.192", "10.2.11.133", "10.2.11.38", "10.2.11.8", "10.2.11.4", "10.2.11.151", "10.2.11.25", "10.2.11.63", "10.2.11.131", "10.2.11.119", "10.2.11.55", "10.2.11.20", "10.2.11.89", "10.2.10.123"}
	set newWindow to (create window with default profile)
	tell newWindow
		tell current session of current tab
			set columns to 200
			set rows to 60
			set fullCmd to cmd & internalHost
			write text fullCmd
		end tell
		repeat with host in hosts
			set newTab to (create tab with default profile)
			set fullCmd to cmd & host
			tell current session of newTab
				write text fullCmd
			end tell
		end repeat
		select first tab
	end tell
end tell
