#!/bin/bash

while :; do
    if [[ -z "$1" ]]; then
        break
    fi

    case $1 in
        -s|--sidecar)
        SIDECAR_CONTAINER="1"
        ;;
        -h|--help)
        echo "pod-container <pod-name> [options...]"
        echo " -s, --sidecar select sidecar container instead of app container"
        exit 0
        ;;
        *)
        if [[ -z "$POD_NAME" ]]; then
            POD_NAME=$1
        fi
        ;;
    esac
    shift
done

if [[ $SIDECAR_CONTAINER == "1" ]]; then
    container=$(kubectl get pods $POD_NAME -o jsonpath='{range .spec.containers[*]}{.name}{"\n"}{end}' | grep istio-proxy)
else
    container=$(kubectl get pods $POD_NAME -o jsonpath='{range .spec.containers[*]}{.name}{"\n"}{end}' | grep -v istio)
fi

echo $container