#!/bin/bash

MOUNT_SOURCE_HOME=/Volumes/External

CLEANUP_TARGECTS=(
    "/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform"
    "/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform"
    "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform"
    "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform"
    "/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform"
    "/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform" 
)

MOUNT_TARGECTS=(
    "$HOME/.go"
    "$HOME/.npm"
    "$HOME/.vscode"
    "$HOME/.m2"
    "$HOME/.gradle"
    "$HOME/.sdkman"
    "$HOME/Library/Caches/JetBrains"
    "$HOME/Library/Caches/go-build"
    "$HOME/Library/Caches/Homebrew"
    "$HOME/Library/Application Support/JetBrains"
    "$HOME/Library/Application Support/Code"
    "$HOME/Library/Developer/CoreSimulator/Caches"
    "$HOME/Library/Logs/JetBrains"
    "$HOME/Music/Music"
    "/private/var/tmp/_bazel_$USER"
)

for t in "${MOUNT_TARGECTS[@]}"; do
    if [[ -d "${t}" ]] && [[ ! -L "${t}" ]] && [[ -d "${MOUNT_SOURCE_HOME}${t}" ]] && [[ ! -L "${MOUNT_SOURCE_HOME}${t}" ]]; then
        echo "Exist in two place, failed to process ${t}, please do it manually."
        continue
    fi

    mkdir -p "${MOUNT_SOURCE_HOME}${t}"
    if [[ -d "${t}" ]] && [[ ! -L "${t}" ]]; then
        rm -rf "${MOUNT_SOURCE_HOME}${t}"
        mv -v "${t}" "${MOUNT_SOURCE_HOME}${t}"
        ln -s "${MOUNT_SOURCE_HOME}${t}" "${t}"
    else
        rm -rf "${t}"
        ln -s "${MOUNT_SOURCE_HOME}${t}" "${t}"
    fi
done

chmod 700 ${MOUNT_SOURCE_HOME}${HOME}/*

for t in "${CLEANUP_TARGECTS[@]}"; do
    sudo rm -rf "${t}"
done

for app in /Applications/* ; do
    if [[ $(file "$app") == *"MacOS Alias file"* ]]; then
        sudo rm -rf "$app"
    fi
done
ls $MOUNT_SOURCE_HOME/Applications | grep "\.app" | xargs -I{} osascript -e "tell application \"Finder\" to make alias file to POSIX file \"$MOUNT_SOURCE_HOME/Applications/{}\" at POSIX file \"/Applications\""