#!/usr/bin/expect
set timeout 30
set ip [lindex $argv 0]
set username [lindex $argv 1]
set port [lindex $argv 2]
set password [lindex $argv 3]
set target_ip [lindex $argv 4]
set target_username [lindex $argv 5]
set target_port [lindex $argv 6]
set target_password [lindex $argv 7]
set auth_code [lindex $argv 8]

spawn ssh -p $port $username@$ip
expect  {
        "*?assword:*" {
                send "$password\r"
		send "ssh -p $target_port $target_username@$target_ip\n"
		expect {
	        	"*(yes/no)*" {
                		send "yes\r"
                		exp_continue
        		}
        		"*?assword:*" {
                		send "$target_password\r"
				interact	
			}
		}
        }
	"*erification code*" {
		send "$auth_code\r"
                exp_continue
	}
        "*(yes/no)*" {
                send "yes\r"
                exp_continue
        }
}
