#!/bin/bash

if [ "$TOMCAT_HOME" = "" ]; then
    echo "Missing \`TOMCAT_TOME environment variable\`"
    exit 1
fi

print_targets () {
    echo "==================== Installed targets ===================="
    find $TOMCAT_HOME/webapps -maxdepth 1 -type l | xargs ls -l
    echo "==========================================================="
}


if [ "$1" = "list" ]; then
    print_targets
elif [ "$1" = "install" ]; then
    MODULE=$2
    TARGET=$3
    if [ "$MODULE" = "" ]; then
        echo "Missing module name!"
        exit 1
    fi
    if [ "$TARGET" = "" ]; then
        TARGET="ROOT"
    fi
    rm -rf "$TOMCAT_HOME/webapps/$TARGET"
    find "$MODULE/target" -maxdepth 1 -type d -name "$MODULE-*" | xargs -I {} ln -s "$PWD/{}" "$TOMCAT_HOME/webapps/$TARGET"
    print_targets
elif [ "$1" = "uninstall" ]; then
    TARGET=$2
    rm -rf "$TOMCAT_HOME/webapps/$TARGET"
elif [ "$1" = "cleanup" ]; then
    print_targets
    echo ""
    read -p "Continue to cleanup (y/N)?" choice
    case "$choice" in 
    y|Y ) find $TOMCAT_HOME/webapps -maxdepth 1 -type l | xargs rm -rf;;
    * ) echo "abort!";;
    esac
else
    echo "commands:
  install module [target]       install module to tomcat, if target is empty will install to ROOT
  uninstall [target]            uninstall target, if target is emptu will uninstall ROOT
  cleanup                       uninstall all installed targets
"
fi

