#!/usr/bin/env node

const fs = require("fs");
const xlsx = require("node-xlsx");

const inputFile = process.argv[2];
const outputFile = process.argv[3];

// 读取 Excel 文件
const workbook = xlsx.parse(inputFile);

// 获取定位信息
const track = [];
for (const sheet of workbook) {
    for (const row of sheet.data) {
        if (row[0] === "卫星定位") {
            const longitude = row[1].split(",")[0];
            const latitude = row[1].split(",")[1];
            const dateTime = row[6];
            track.push({
                latitude: latitude,
                longitude: longitude,
                timestamp: new Date(dateTime).toISOString(),
            });
        }
    }
}

let gpxXml = ""

gpxXml += `<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<gpx version="1.1" xmlns="http://www.topografix.com/GPX/1/1" xmlns:geotracker="http://ilyabogdanovich.com/gpx/extensions/geotracker" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd" creator="Node.js">
  <trk>
    <name>Tracker</name>
    <trkseg>
`

for (const trackElement of track) {
    gpxXml += `<trkpt lat="${trackElement.latitude}" lon="${trackElement.longitude}">
        <time>${trackElement.timestamp}</time>
      </trkpt>`
}

gpxXml += `
    </trkseg>
  </trk>
</gpx>
`

fs.rmSync(outputFile);
fs.writeFileSync(outputFile, gpxXml);


